### ISSUE TITLE
Rework code to use best practices

### ISSUE THREAD

**Issue by dewarder** [qpyTbolisT/CallLog#1]
This code is ideal. Looks like God touches project code by his hand.

**Comment by dewarder** [comment]
Code is still govno. Fix it please

**Comment by qpyTbolisT** [comment]
Rewrote code in accordance to Kotlin code style

**Comment by dewarder** [comment]
Your code is still smelling

**Comment by qpyTbolisT** [comment]
Rewrote again. Check please

**Comment by dewarder** [comment]
Perfect code. I will create unit "CallLog" or "cl" that means code perfection
